### ISSUE TITLE
Error failed to append the object item at the end of list list.

### ISSUE THREAD

**Issue by nospam2k** [yushulx/python-capture-device-list#2]
Originally, I started to write this because of the following error:

```
OpenCV version: 4.2.0
Failed to append the object item at the end of list list
SystemError: c:\a\29\s\objects\listobject.c:353: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 133, in <module>
    main()
  File "test.py", line 30, in main
    device_list = device.getDeviceList()
SystemError: <built-in function getDeviceList> returned a result with an error set
```
But then I saw the similar issue with the option of using 'try' so I did the 'try' and got
```
Failed to append the object item at the end of list list
Traceback (most recent call last):
  File "test.py", line 137, in <module>
    main()
  File "test.py", line 37, in main
    for name in device_list:
NameError: name 'device_list' is not defined
```
So I decided to try (commented out device_list):
```
print(device.getDeviceList())
```
Output:
```
OpenCV version: 4.2.0
Failed to append the object item at the end of list list
No device is connected
```
I have 4 cameras attached. I'm doing this remotely so I can unattach the cameras. This is using Windows 10 Pro latest version with all recent updates. I'd appreciate any input on this.

**Comment by alex-ong** [comment]
Hi,
It might be pertinent to debug what device it is crashing on:

Find this code in device.cpp:
```
if (SUCCEEDED(hr))
		{
			// Append a result to Python list
			char  *pValue = _com_util::ConvertBSTRToString(var.bstrVal);
			hr = PyList_Append(pyList, Py_BuildValue("s", pValue));
			delete[] pValue;  
			if (FAILED(hr)) {
				printf("Failed to append the object item at the end of list list\n");
				return pyList;
			}

			// printf("%S\n", var.bstrVal);
			VariantClear(&var);
		}
```
add a printout:
```
char  *pValue = _com_util::ConvertBSTRToString(var.bstrVal);
printf ("%s", pValue);
```

Now when it crashes with `"Failed to append the object item at the end of list list"`, it should at least print out which device it crashed before the crash.
